DELIMITER //
DROP PROCEDURE IF EXISTS this_procedure;
CREATE PROCEDURE this_procedure()
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
    DECLARE EXIT HANDLER FOR SQLWARNING BEGIN ROLLBACK; RESIGNAL; END;
    DECLARE CONTINUE HANDLER FOR 1091 BEGIN END;
    DECLARE CONTINUE HANDLER FOR 1054 BEGIN END;
    DECLARE EXIT HANDLER FOR 1062 BEGIN ROLLBACK; RESIGNAL; END;
    START TRANSACTION;
        SET FOREIGN_KEY_CHECKS=0;
        ALTER TABLE `catalog_category_entity`
            DROP FOREIGN KEY `CAT_CTGR_ENTT_ENTT_ID_SEQUENCE_CAT_CTGR_SEQUENCE_VAL`;
        ALTER TABLE `catalog_category_entity_datetime`
            DROP FOREIGN KEY `CAT_CTGR_ENTT_DTIME_ROW_ID_CAT_CTGR_ENTT_ROW_ID`;
        ALTER TABLE `catalog_category_entity_decimal`
            DROP FOREIGN KEY `CAT_CTGR_ENTT_DEC_ROW_ID_CAT_CTGR_ENTT_ROW_ID`;
        ALTER TABLE `catalog_category_entity_int`
            DROP FOREIGN KEY `CAT_CTGR_ENTT_INT_ROW_ID_CAT_CTGR_ENTT_ROW_ID`;
        ALTER TABLE `catalog_category_entity_text`
            DROP FOREIGN KEY `CAT_CTGR_ENTT_TEXT_ROW_ID_CAT_CTGR_ENTT_ROW_ID`;
        ALTER TABLE `catalog_category_entity_varchar`
            DROP FOREIGN KEY `CAT_CTGR_ENTT_VCHR_ROW_ID_CAT_CTGR_ENTT_ROW_ID`;
        ALTER TABLE `catalog_category_product`
            DROP FOREIGN KEY `CAT_CTGR_PRD_CTGR_ID_SEQUENCE_CAT_CTGR_SEQUENCE_VAL`,
            DROP FOREIGN KEY `CAT_CTGR_PRD_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_compare_item`
            DROP FOREIGN KEY `CATALOG_COMPARE_ITEM_PRODUCT_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `catalog_product_bundle_option`
            DROP FOREIGN KEY `CAT_PRD_BNDL_OPT_PARENT_ID_CAT_PRD_ENTT_ROW_ID`,
            DROP FOREIGN KEY `CAT_PRD_BNDL_OPT_OPT_ID_SEQUENCE_PRD_BNDL_OPT_SEQUENCE_VAL`;
        ALTER TABLE `catalog_product_bundle_option_value`
            DROP FOREIGN KEY `CAT_PRD_BNDL_OPT_VAL_OPT_ID_SEQUENCE_PRD_BNDL_OPT_SEQUENCE_VAL`,
            DROP FOREIGN KEY `CAT_PRD_BNDL_OPT_VAL_PARENT_PRD_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_bundle_price_index`
            DROP FOREIGN KEY `CAT_PRD_BNDL_PRICE_IDX_ENTT_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_product_bundle_selection`
            DROP FOREIGN KEY `CAT_PRD_BNDL_SELECTION_OPT_ID_SEQUENCE_PRD_BNDL_OPT_SEQUENCE_VAL`,
            DROP FOREIGN KEY `CAT_PRD_BNDL_SELECTION_PARENT_PRD_ID_CAT_PRD_ENTT_ROW_ID`,
            DROP FOREIGN KEY `CAT_PRD_BNDL_SELECTION_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`,
            DROP FOREIGN KEY `FK_606117FEB5F50D0182CEC9D260C05DD2`;
        ALTER TABLE `catalog_product_bundle_selection_price`
            DROP FOREIGN KEY `CAT_PRD_BNDL_SELECTION_PRICE_PARENT_PRD_ID_CAT_PRD_ENTT_ROW_ID`,
            DROP FOREIGN KEY `FK_AE9FDBF7988FB6BE3E04D91DA2CFB273`;
        ALTER TABLE `catalog_product_entity`
            DROP FOREIGN KEY `CATALOG_PRODUCT_ENTITY_ENTITY_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `catalog_product_entity_datetime`
            DROP FOREIGN KEY `CAT_PRD_ENTT_DTIME_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_entity_decimal`
            DROP FOREIGN KEY `CAT_PRD_ENTT_DEC_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_entity_gallery`
            DROP FOREIGN KEY `CAT_PRD_ENTT_GLR_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_entity_int`
            DROP FOREIGN KEY `CATALOG_PRODUCT_ENTITY_INT_ROW_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`;
        ALTER TABLE `catalog_product_entity_media_gallery_value`
            DROP FOREIGN KEY `CAT_PRD_ENTT_MDA_GLR_VAL_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_entity_media_gallery_value_to_entity`
            DROP FOREIGN KEY `CAT_PRD_ENTT_MDA_GLR_VAL_TO_ENTT_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_entity_text`
            DROP FOREIGN KEY `CATALOG_PRODUCT_ENTITY_TEXT_ROW_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`;
        ALTER TABLE `catalog_product_entity_tier_price`
            DROP FOREIGN KEY `CAT_PRD_ENTT_TIER_PRICE_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_entity_varchar`
            DROP FOREIGN KEY `CAT_PRD_ENTT_VCHR_ROW_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_index_tier_price`
            DROP FOREIGN KEY `CAT_PRD_IDX_TIER_PRICE_ENTT_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_product_link`
            DROP FOREIGN KEY `CATALOG_PRODUCT_LINK_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`,
            DROP FOREIGN KEY `CAT_PRD_LNK_LNKED_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_product_option`
            DROP FOREIGN KEY `CATALOG_PRODUCT_OPTION_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`;
        ALTER TABLE `catalog_product_relation`
            DROP FOREIGN KEY `CATALOG_PRODUCT_RELATION_PARENT_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`,
            DROP FOREIGN KEY `CAT_PRD_RELATION_CHILD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_product_super_attribute`
            DROP FOREIGN KEY `CAT_PRD_SPR_ATTR_PRD_ID_CAT_PRD_ENTT_ROW_ID`;
        ALTER TABLE `catalog_product_super_link`
            DROP FOREIGN KEY `CAT_PRD_SPR_LNK_PARENT_ID_CAT_PRD_ENTT_ROW_ID`,
            DROP FOREIGN KEY `CAT_PRD_SPR_LNK_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_product_website`
            DROP FOREIGN KEY `CAT_PRD_WS_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalog_url_rewrite_product_category`
            DROP FOREIGN KEY `CAT_URL_REWRITE_PRD_CTGR_CTGR_ID_SEQUENCE_CAT_CTGR_SEQUENCE_VAL`,
            DROP FOREIGN KEY `CAT_URL_REWRITE_PRD_CTGR_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `cataloginventory_stock_item`
            DROP FOREIGN KEY `CATINV_STOCK_ITEM_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `catalogrule`
            DROP FOREIGN KEY `CATALOGRULE_RULE_ID_SEQUENCE_CATALOGRULE_SEQUENCE_VALUE`;
        ALTER TABLE `catalogrule_customer_group`
            DROP FOREIGN KEY `CATALOGRULE_CUSTOMER_GROUP_ROW_ID_CATALOGRULE_ROW_ID`;
        ALTER TABLE `catalogrule_website`
            DROP FOREIGN KEY `CATALOGRULE_WEBSITE_ROW_ID_CATALOGRULE_ROW_ID`;
        ALTER TABLE `cms_block`
            DROP FOREIGN KEY `CMS_BLOCK_BLOCK_ID_SEQUENCE_CMS_BLOCK_SEQUENCE_VALUE`;
        ALTER TABLE `cms_block_store`
            DROP FOREIGN KEY `CMS_BLOCK_STORE_ROW_ID_CMS_BLOCK_ROW_ID`;
        ALTER TABLE `cms_page`
            DROP FOREIGN KEY `CMS_PAGE_PAGE_ID_SEQUENCE_CMS_PAGE_SEQUENCE_VALUE`;
        ALTER TABLE `cms_page_store`
            DROP FOREIGN KEY `CMS_PAGE_STORE_ROW_ID_CMS_PAGE_ROW_ID`;
        ALTER TABLE `downloadable_link`
            DROP FOREIGN KEY `DOWNLOADABLE_LINK_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`;
        ALTER TABLE `downloadable_sample`
            DROP FOREIGN KEY `DOWNLOADABLE_SAMPLE_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ROW_ID`;
        ALTER TABLE `email_catalog`
            DROP FOREIGN KEY `EMAIL_CATALOG_PRODUCT_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `product_alert_price`
            DROP FOREIGN KEY `PRODUCT_ALERT_PRICE_PRODUCT_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `product_alert_stock`
            DROP FOREIGN KEY `PRODUCT_ALERT_STOCK_PRODUCT_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `report_compared_product_index`
            DROP FOREIGN KEY `REPORT_CMPD_PRD_IDX_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `report_viewed_product_aggregated_daily`
            DROP FOREIGN KEY `REPORT_VIEWED_PRD_AGGRED_DAILY_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `report_viewed_product_aggregated_monthly`
            DROP FOREIGN KEY `FK_0140003A30AFC1A9188D723C4634BA5D`;
        ALTER TABLE `report_viewed_product_aggregated_yearly`
            DROP FOREIGN KEY `REPORT_VIEWED_PRD_AGGRED_YEARLY_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `report_viewed_product_index`
            DROP FOREIGN KEY `REPORT_VIEWED_PRD_IDX_PRD_ID_SEQUENCE_PRD_SEQUENCE_VAL`;
        ALTER TABLE `salesrule`
            DROP FOREIGN KEY `SALESRULE_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE`;
        ALTER TABLE `salesrule_coupon`
            DROP FOREIGN KEY `SALESRULE_COUPON_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE`;
        ALTER TABLE `salesrule_customer`
            DROP FOREIGN KEY `SALESRULE_CUSTOMER_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE`;
        ALTER TABLE `salesrule_customer_group`
            DROP FOREIGN KEY `SALESRULE_CUSTOMER_GROUP_ROW_ID_SALESRULE_ROW_ID`;
        ALTER TABLE `salesrule_label`
            DROP FOREIGN KEY `SALESRULE_LABEL_RULE_ID_SEQUENCE_SALESRULE_SEQUENCE_VALUE`;
        ALTER TABLE `salesrule_product_attribute`
            DROP FOREIGN KEY `SALESRULE_PRODUCT_ATTRIBUTE_ROW_ID_SALESRULE_ROW_ID`;
        ALTER TABLE `salesrule_website`
            DROP FOREIGN KEY `SALESRULE_WEBSITE_ROW_ID_SALESRULE_ROW_ID`;
        ALTER TABLE `weee_tax`
            DROP FOREIGN KEY `WEEE_TAX_ENTITY_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `wishlist_item`
            DROP FOREIGN KEY `WISHLIST_ITEM_PRODUCT_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`;
        ALTER TABLE `amasty_banners_lite_banner_data`
            DROP FOREIGN KEY `AMASTY_BANNERS_LITE_BANNER_DATA_SALESRULE_ID_SALESRULE_RULE_ID`;
        ALTER TABLE `amasty_banners_lite_rule`
            DROP FOREIGN KEY `AMASTY_BANNERS_LITE_RULE_SALESRULE_ID_SALESRULE_RULE_ID`;
        ALTER TABLE `amasty_amrules_rule`
            DROP FOREIGN KEY `AMASTY_AMRULES_RULE_SALESRULE_ID_SALESRULE_ROW_ID`;
        ALTER TABLE `catalog_product_frontend_action`
            DROP FOREIGN KEY `CAT_PRD_FRONTEND_ACTION_PRD_ID_CAT_PRD_ENTT_ENTT_ID`;
        ALTER TABLE `catalog_product_frontend_action`
            DROP FOREIGN KEY `CAT_PRD_FRONTEND_ACTION_PRD_ID_CAT_PRD_ENTT_ENTT_ID`;
        ALTER TABLE `amasty_blog_posts_products`
            DROP FOREIGN KEY `AMASTY_BLOG_POSTS_PRDS_PRD_ID_CAT_PRD_ENTT_ENTT_ID`;
        ALTER TABLE `globale_fixed_price`
            DROP FOREIGN KEY `GLOBALE_FIXED_PRICE_ENTITY_ID_CATALOG_PRODUCT_ENTITY_ENTITY_ID`;
        ALTER TABLE `wclprima_stock_item`
            DROP FOREIGN KEY `WCLPRIMA_STOCK_ITEM_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ENTITY_ID`;
        ALTER TABLE `salesrule_label`
            DROP FOREIGN KEY `SALESRULE_LABEL_ROW_ID_SALESRULE_ROW_ID`;
        ALTER TABLE `amasty_amrules_usage_counter`
            DROP FOREIGN KEY `AMASTY_AMRULES_USAGE_COUNTER_SALESRULE_ID_SALESRULE_RULE_ID`;
        SET FOREIGN_KEY_CHECKS=1;
    COMMIT;
END
//
DELIMITER ;
CALL this_procedure();
